import type { Patient, SectorType } from "@/types/patient";
import type { Database, Json } from "@/integrations/supabase/types";
import { birthDateToISO } from "@/utils/calculateDetailedAge";

type PatientRow = Database["public"]["Tables"]["patients"]["Row"];
type PatientUpdate = Database["public"]["Tables"]["patients"]["Update"];

const linesToText = (value: unknown): string | null => {
  if (Array.isArray(value)) return value.filter(Boolean).join("\n") || null;
  if (typeof value === "string") return value.trim() ? value : null;
  return null;
};

const normalizedAge = (value: unknown): string | null => {
  if (value === undefined || value === null || value === "") return null;
  return String(value);
};

const asJson = (value: unknown): Json | null => (value ? (value as Json) : null);

export const vacantPatientSlotPayload: PatientUpdate = {
  name: "",
  age: null,
  birth_date: null,
  diagnoses: null,
  medical_history: null,
  relevant_exams: null,
  pendencies: null,
  schedule: null,
  admission_history: null,
  admission_date: null,
  medical_responsibility: null,
  internment_status: null,
  internment_notes: null,
  is_door_patient: false,
  allocation_status: null,
  psm_status: null,
  clinical_status: null,
  patient_category: null,
  medical_record_number: null,
  attendance_number: null,
  cpf: null,
  mother_name: null,
  insurance_company: null,
  insurance_plan: null,
  insurance_plan_type: null,
  insurance_card_number: null,
  insurance_duration: null,
  highlighted_pendencies: [],
  highlighted_diagnoses: [],
  highlighted_medical_history: [],
  highlighted_conducts: [],
  uti_admission_date: null,
  uti_discharge_prediction: null,
  uti_allergies: null,
  uti_admission_reason: null,
  uti_current_status: null,
  uti_devices: null,
  uti_cultures_antibiotics: null,
  uti_specialties: null,
  uti_origin_sector: null,
  uti_daily_conducts: null,
  is_vacant: true,
  bed_status: "available",
  bed_maintenance_reason: null,
  bed_maintenance_started_at: null,
  bed_maintenance_started_by: null,
} as const;

export const buildPatientSlotPayloadFromPatient = (patient: Patient, destinationSector: SectorType): PatientUpdate => ({
  name: patient.name || "",
  age: normalizedAge(patient.age),
  birth_date: birthDateToISO(patient.birthDate),
  diagnoses: linesToText(patient.diagnoses),
  medical_history: linesToText(patient.medicalHistory),
  relevant_exams: linesToText(patient.relevantExams),
  pendencies: linesToText(patient.pendencies),
  schedule: linesToText(patient.schedule),
  admission_history: patient.admissionHistory || null,
  admission_date: patient.admissionDate || null,
  medical_responsibility: asJson(patient.medicalResponsibility),
  internment_status: patient.internmentStatus || null,
  internment_notes: patient.internmentNotes || null,
  is_door_patient: destinationSector === "outside",
  allocation_status: patient.allocationStatus || null,
  psm_status: patient.psmStatus || null,
  clinical_status: patient.clinicalStatus || null,
  patient_category: patient.patientCategory || null,
  medical_record_number: patient.medicalRecordNumber || null,
  attendance_number: patient.attendanceNumber || null,
  cpf: patient.cpf || null,
  mother_name: patient.motherName || null,
  insurance_company: patient.insuranceCompany || null,
  insurance_plan: patient.insurancePlan || null,
  insurance_plan_type: patient.insurancePlanType || null,
  insurance_card_number: patient.insuranceCardNumber || null,
  insurance_duration: patient.insuranceDuration || null,
  highlighted_pendencies: patient.highlightedPendencies || [],
  highlighted_diagnoses: patient.highlightedDiagnoses || [],
  highlighted_medical_history: patient.highlightedMedicalHistory || [],
  highlighted_conducts: patient.highlightedConducts || [],
  uti_admission_date: linesToText(patient.utiAdmissionDate),
  uti_discharge_prediction: linesToText(patient.utiDischargePrediction),
  uti_allergies: linesToText(patient.utiAllergies),
  uti_admission_reason: linesToText(patient.utiAdmissionReason),
  uti_current_status: linesToText(patient.utiCurrentStatus),
  uti_devices: linesToText(patient.utiDevices),
  uti_cultures_antibiotics: linesToText(patient.utiCulturesAntibiotics),
  uti_specialties: linesToText(patient.utiSpecialties),
  uti_origin_sector: linesToText(patient.utiOriginSector),
  uti_daily_conducts: linesToText(patient.utiDailyConducts),
  is_vacant: false,
  bed_status: "available",
  bed_maintenance_reason: null,
  bed_maintenance_started_at: null,
  bed_maintenance_started_by: null,
});

export const buildPatientSlotPayloadFromRecord = (record: PatientRow, destinationSector: SectorType): PatientUpdate => ({
  name: record.name || "",
  age: normalizedAge(record.age),
  birth_date: record.birth_date || null,
  diagnoses: record.diagnoses || null,
  medical_history: record.medical_history || null,
  relevant_exams: record.relevant_exams || null,
  pendencies: record.pendencies || null,
  schedule: record.schedule || null,
  admission_history: record.admission_history || null,
  admission_date: record.admission_date || null,
  medical_responsibility: record.medical_responsibility || null,
  internment_status: record.internment_status || null,
  internment_notes: record.internment_notes || null,
  is_door_patient: destinationSector === "outside",
  allocation_status: record.allocation_status || null,
  psm_status: record.psm_status || null,
  clinical_status: record.clinical_status || null,
  patient_category: record.patient_category || null,
  medical_record_number: record.medical_record_number || null,
  attendance_number: record.attendance_number || null,
  cpf: record.cpf || null,
  mother_name: record.mother_name || null,
  insurance_company: record.insurance_company || null,
  insurance_plan: record.insurance_plan || null,
  insurance_plan_type: record.insurance_plan_type || null,
  insurance_card_number: record.insurance_card_number || null,
  insurance_duration: record.insurance_duration || null,
  highlighted_pendencies: record.highlighted_pendencies || [],
  highlighted_diagnoses: record.highlighted_diagnoses || [],
  highlighted_medical_history: record.highlighted_medical_history || [],
  highlighted_conducts: record.highlighted_conducts || [],
  uti_admission_date: record.uti_admission_date || null,
  uti_discharge_prediction: record.uti_discharge_prediction || null,
  uti_allergies: record.uti_allergies || null,
  uti_admission_reason: record.uti_admission_reason || null,
  uti_current_status: record.uti_current_status || null,
  uti_devices: record.uti_devices || null,
  uti_cultures_antibiotics: record.uti_cultures_antibiotics || null,
  uti_specialties: record.uti_specialties || null,
  uti_origin_sector: record.uti_origin_sector || null,
  uti_daily_conducts: record.uti_daily_conducts || null,
  is_vacant: false,
  bed_status: "available",
  bed_maintenance_reason: null,
  bed_maintenance_started_at: null,
  bed_maintenance_started_by: null,
});

export const buildPatientSlotPayloadFromSnapshot = (snapshot: Partial<Patient> | null | undefined, fallbackName: string, destinationSector: SectorType): PatientUpdate => ({
  name: snapshot?.name || fallbackName || "",
  age: normalizedAge(snapshot?.age),
  birth_date: birthDateToISO(snapshot?.birthDate) || null,
  diagnoses: linesToText(snapshot?.diagnoses),
  medical_history: linesToText(snapshot?.medicalHistory),
  relevant_exams: linesToText(snapshot?.relevantExams),
  pendencies: linesToText(snapshot?.pendencies),
  schedule: linesToText(snapshot?.schedule),
  admission_history: snapshot?.admissionHistory || null,
  admission_date: snapshot?.admissionDate || new Date().toISOString(),
  medical_responsibility: asJson(snapshot?.medicalResponsibility),
  internment_status: snapshot?.internmentStatus || null,
  internment_notes: snapshot?.internmentNotes || null,
  is_door_patient: destinationSector === "outside",
  allocation_status: snapshot?.allocationStatus || null,
  psm_status: snapshot?.psmStatus || null,
  clinical_status: snapshot?.clinicalStatus || null,
  patient_category: snapshot?.patientCategory || null,
  medical_record_number: snapshot?.medicalRecordNumber || null,
  attendance_number: snapshot?.attendanceNumber || null,
  cpf: snapshot?.cpf || null,
  mother_name: snapshot?.motherName || null,
  insurance_company: snapshot?.insuranceCompany || null,
  insurance_plan: snapshot?.insurancePlan || null,
  insurance_plan_type: snapshot?.insurancePlanType || null,
  insurance_card_number: snapshot?.insuranceCardNumber || null,
  insurance_duration: snapshot?.insuranceDuration || null,
  highlighted_pendencies: snapshot?.highlightedPendencies || [],
  highlighted_diagnoses: snapshot?.highlightedDiagnoses || [],
  highlighted_medical_history: snapshot?.highlightedMedicalHistory || [],
  highlighted_conducts: snapshot?.highlightedConducts || [],
  uti_admission_date: linesToText(snapshot?.utiAdmissionDate),
  uti_discharge_prediction: linesToText(snapshot?.utiDischargePrediction),
  uti_allergies: linesToText(snapshot?.utiAllergies),
  uti_admission_reason: linesToText(snapshot?.utiAdmissionReason),
  uti_current_status: linesToText(snapshot?.utiCurrentStatus),
  uti_devices: linesToText(snapshot?.utiDevices),
  uti_cultures_antibiotics: linesToText(snapshot?.utiCulturesAntibiotics),
  uti_specialties: linesToText(snapshot?.utiSpecialties),
  uti_origin_sector: linesToText(snapshot?.utiOriginSector),
  uti_daily_conducts: linesToText(snapshot?.utiDailyConducts),
  is_vacant: false,
  bed_status: "available",
  bed_maintenance_reason: null,
  bed_maintenance_started_at: null,
  bed_maintenance_started_by: null,
});